# Oyster theme defaults

menu: {}

search:
  enabled: true
  path: /search/
  index: /search.json

favicon: /img/favicon.ico

excerpt_length: 560

markdown_outline: true

language_switch: true

footer:
  since: 2025

custom_css:
  - /css/custom.css

custom_js:
  - /js/homepage-links.js
